services:

  Rollbar\Symfony\RollbarBundle\Factories\RollbarHandlerFactory:
    arguments:
      - '@service_container'
      - '@serializer'
      - '@?security.helper'

  Rollbar\Monolog\Handler\RollbarHandler:
    factory: ['@Rollbar\Symfony\RollbarBundle\Factories\RollbarHandlerFactory', createRollbarHandler]
    tags:
      - { name: monolog.logger, channel: rollbar }

  Rollbar\Symfony\RollbarBundle\Payload\Generator:
    arguments:
      - '@service_container'
